---
- hosts: all
  become: yes
  tasks:

    # for default setting
    - name: Change timezone from UTC to JST
      file:
        src: /usr/share/zoneinfo/Asia/Tokyo
        dest: /etc/localtime
        owner: root
        group: root
        state: link
    - name: Install package vim
      yum: pkg=vim state=latest
    - name: Install package epel-release
      yum: name=https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-7-11.noarch.rpm
    - name: Install package htop
      yum: pkg=htop state=latest

    # for git setting
    - name: Install necessary package for git complile
      yum: pkg={{ item }} state=latest
      with_items:
      - wget
      - gcc
    - name: Install dependent packages for git
      yum: pkg={{ item }} state=latest
      with_items:
      - curl-devel
      - expat-devel
      - gettext-devel
      - openssl-devel
      - perl-devel
      - zlib-devel
    - name: Download git tarball
      get_url:
        url: https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.22.0.tar.gz
        dest: /usr/local/src/git-2.22.0.tar.gz
    - name: Untar git tarball
      unarchive:
        src: /usr/local/src/git-2.22.0.tar.gz
        dest: /usr/local/src
        remote_src: yes
    - name: Configure git src
      shell: ./configure --prefix=/usr
      args:
        chdir: /usr/local/src/git-2.22.0
    - name: Make all for git
      make:
        chdir: /usr/local/src/git-2.22.0
        target: all
    - name: Make install for git
      make:
        chdir: /usr/local/src/git-2.22.0
        target: install

    # for docker setting
    - name: Add docker-ce repository
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - name: Install package docker
      yum: pkg=docker-ce-18.06.3.ce-3.el7 state=latest

    # for docker-compose setting
    - name: Fetch and Install package docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.24.0/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        owner: root
        group: root
        mode: '0755'
    - name: Set user group to vagrant user for using docker-compose
      user:
        name: vagrant
        group: vagrant
        groups: docker
    - name: Restart docker deamon for setting docker-compose
      shell: systemctl restart docker
